remote_theme: koshikraj/portfolio-theme  # Don't touch ( required for this theme)

# Edit your preferences below
title: Koshik Raj
subtitle: Blockchain - Author | Speaker | Enterpreneur | Evalngelist
description: >- # this means to ignore newlines until "baseurl:"

url: "https://koshikraj.com" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
#    - text: Blog
#      url: /blog
    - text: About Me
      url: /about
    - text: Contact Me
      url : /contact
    - text: Purchase
      url: https://theblockchainbook.info
    - text: Talks
      url: https://talks.koshikraj.com
    - text: More
      url: https://portfolio.koshikraj.com


# Edit these details

author_logo: profile.png
author: Koshik Raj
author_bio: Hello there, not to boast, but I'am clear logical thinker. I design algorithms for every problem in my life unknowingly. I speak, read, write and build on decentralized protocols. I like to solve lot of puzzles (Yeah! I'am a speed cuber as well) and learn new technologies. <a href="https://portfolio.koshikraj.com">Read More</a>.
author_email: "koshik@consensolabs.com"
author_location: Bangalore, India
author_website_url: "https://koshikraj.com"

author_work_experiences:
            - company_name: Consenso Labs
              company_logo: company4.jpeg
              company_url: https://consensolabs.com
              designation: Co-Founder, Lead Developer
              description: Founded a blockchain research lab where we solve some of the financial and open economics use cases through Enterprise and public DLT protocols
              visibility: true
            - company_name: Amity Online
              company_logo: company3.png
              company_url: https://amityonline.com
              designation: Blockchain Faculty
              description: Faculty for Blockchain Program (PGD-BTM)
              visibility: true
            - company_name: CoWrks
              company_logo: company2.png
              company_url: https://cowrks.com
              designation: Senior Developer
              description: Worked as a full-stack developer/ product architect along with the managerial responsibilities to build and ship flagship products.
              visibility: true
            - company_name: RSA Security
              company_logo: company1.png
              company_url: https://www.rsa.com
              designation: Associate Software Engineer
              description: Worked on the RSA's flagship network and log analytics tool "Security Analytics"
              visibility: true

author_education_details:
              - college_logo: college2.png
                college_name: Manipal Institute of Technology
                college_url: https://manipal.edu
                college_degree: Major - Computer Science and Information Security
                description: Master of Technology (M.Tech)
                visibility: true
              - college_logo: college1.png
                college_name: Visvesvaraya Technological University
                college_url: http://www.vtu.ac.in
                college_degree: Computer Science Engineer
                description: Bachelor of Technology
                visibility: true

author_project_details:
              - project_thumbnail: syndlend.jpeg
                project_title: Lead Developer/Architect - SyndLend
                project_description: DLT based syndicated loan platform to create a speedy, cost efficient, transparent, dis-intermediated, yet compliant system.
                project_url: https://syndlend.consensolabs.com
                visibility: true
              - project_thumbnail: gitfunded.png
                project_title: Developer/Architect -GitFunded
                project_description:  A decentralized platform to fund the GitHub projects and manage the funds in a fair and transparent way
                project_url: https://gitfunded.consensolabs.com
                visibility: true
              - project_thumbnail: theblockchainbook.jpeg
                project_title: Author - Foundations of Blockchain
                project_description: Authored a book on blockchain technology titled "Foundations of Blockchain" - The pathway to cryptocurrencies and decentralized blockchain applications
                project_url: https://author.koshikraj.com
                visibility: true

# social links
twitter_username: rajkoshik
github_username:  koshikraj
facebook_username: koshikraj
linkedin_username: koshikraj
medium_username: koshikraj
telegram_username: koshikraj
quora_username: Koshik-Raj

#for comments using disqus
disqus_shortname: koshikraj

# wakatime username
wakatime_username: sujaykundu777

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
#google_analytics: UA-46783401-10

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
  # - jekyll-archives

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


